HOST: devs.in

--- DevSin ---

--
Team Resourses
The following section contains the operations that can be preformed on the team object
--

Get all the teams that are avalible
GET /api/team
< 200
< Content-Type: application/json
[{"key":"qa","name":"QA","count":0},{"key":"umz0i","name":"The A Team","count":0}]

Create a new team with a passphrase to prevent unauthorized writes
POST /api/team
> Content-Type: application/json
{
"name" : "The A Team",
"passphrase" : "Shut up, fool."
}
< 200
< Content-Type: application/json
{"key":"umz0i","name":"The A Team"}

--
Specific Team Operations
This section is the contains the operations that can preformed on a specific team
--
Get all the posts on a team
GET /api/team/{teamId}
< 200
< Content-Type: application/json
{
    "name":"QA",
    "count":3,
    "sins":[
        {"sinner":"ethan","sin":"broke the build","id":1},
        {"sinner":"james","sin":"broke the build","id":2},
        {"sinner":"andrew","sin":"broke the build","id":3}
        ],
        "hasPassphrase":false,
        "refreshLink":"/api/team/{teamId}"}

Create a new post on a team with no passphrase needed
POST /api/team/{teamId}
> Content-Type: application/json
{"sinner":"ethan", "sin":"broke the build"}
< 200
< Content-Type: application/json
{"count":1,"refreshLink":"/api/team/{teamId}"}
+++++
< 403
< Content-Type: application/json
{
    "error": "Passphrase invalid"
}
+++++
< 404
{
    "error": "Team not found"
}

--
Post specific actions. You can delete and get operations
--
Get the data for a post
GET /api/post/{postId}
< 200
< Content-type: application/json
{"sinner":"ethan","sin":"broke the build","id":6}
+++++
< 404
< Content-type: application/json
{"error":"Post not found"}

Deletes a post
DELETE /api/post/{postId}
< 200
< Content-Type: application/json
{"status":"OK"}
+++++
< 404
< Content-Type: application/json
{"error":"Post not found"}
